addons:
  apt:
    packages:
      - lib32stdc++6
      - lib32z1-dev
      - libc6-dev-i386
      - linux-libc-dev
      - g++-multilib
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test
language: cpp
sudo: false
compiler:
  - clang
env:
  global:
    - LLVM_ARCHIVE_URI=https://www.sourcemod.net/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
    - EMSCRIPTEN_SDK_URI=https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  matrix:
    - AM_CC=clang-3.8 AM_CXX=clang++-3.8 AM_ARCH=x86 AM_TYPE=optimize
    - AM_CC=clang-3.8 AM_CXX=clang++-3.8 AM_ARCH=x86 AM_TYPE=debug
    - AM_CC=clang-3.8 AM_CXX=clang++-3.8 AM_ARCH=x64 AM_TYPE=optimize
    - AM_CC=clang-3.8 AM_CXX=clang++-3.8 AM_ARCH=x64 AM_TYPE=debug
    - AM_CC=emcc AM_CXX=em++ AM_ARCH=x86 AM_TYPE=optimize
    - AM_CC=emcc AM_CXX=em++ AM_ARCH=x86 AM_TYPE=debug
install:
  - source ./tools/travis-download-compiler.sh
  - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/tools/checkout-deps.sh && cd $CHECKOUT_DIR
  - export PATH="~/.local/bin:$PATH"
  - echo $PATH
  - $AM_CC --version
script:
  - mkdir $AM_CC-$AM_ARCH-$AM_TYPE && cd $AM_CC-$AM_ARCH-$AM_TYPE
  - CC=$AM_CC CXX=$AM_CXX python ../configure.py --enable-$AM_TYPE --target-arch=$AM_ARCH
  - ambuild
  - ./testing/test-all.$AM_ARCH.sh
