name: Run tests

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        AM_TYPE: ["optimize", "debug"]
  
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && apt-get install gcc-multilib g++-multilib libstdc++6 lib32stdc++6 libc6-dev libc6-dev-i386 linux-libc-dev linux-libc-dev:i386
      
      - name: Preparing
        run: |
          CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/tools/checkout-deps.sh && cd $CHECKOUT_DIR
          export PATH="~/.local/bin:$PATH"
      
      - name: Get clang++ version
        run: clang++ --version

      - name: Create objdir
        run: |
          mkdir objdir
          cd objdir
      
      - name: Configure
        run: CC=clang CXX=clang++ python ../configure.py --enable-${{ matrix.AM_TYPE }} --targets=x86,x64

      - name: AMBuild
        run: ambuild
      
      - name: Run tests
        run: python $CHECKOUT_DIR/tests/runtests.py .
